name: Publish Core Module to Maven Central

on:
  push:
    tags:
      - 'v*'  # Runs only for version tags (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from Git tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Update pom.xml version
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }} -pl jinputprocessor-core -am

      - name: Run tests
        run: mvn clean test

      - name: Build and package core module
        run: mvn clean install -pl jinputprocessor-core -am

      - name: Publish core module to Maven Central
        run: |
          mvn -P release --batch-mode deploy -am -DskipTests -pl jinputprocessor-core
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Bump to next SNAPSHOT version
        run: |
          NEXT_VERSION=$(echo ${{ env.RELEASE_VERSION }} | awk -F. '{print $1"."$2"."$3+1"-SNAPSHOT"}')
          mvn versions:set -DnewVersion=$NEXT_VERSION -am
          git commit -am "Set version to $NEXT_VERSION"
          git push origin HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

