name: SonarQube Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run SonarQube
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=YOUR_PROJECT_KEY
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}